version: "3.5"
name: "focus-flow-services"
services:
  db:
    image: "postgres"
    restart: always
    container_name: focus-flow-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "focus-flow"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432

volumes:
  database-data:
